---
title: "Trainer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages

```{r}
pacman::p_load(tidyverse, purrr, furrr, keras, xgboost, h2o)
devtools::document()
#devtools::load_all()
options(scipen = 999)
# devtools::install()
```




# Test Data

```{r}
N <- 1000
df <- tibble(
  split_id = sample(1:3, size = N, prob = c(.8, .1, .1), replace = T),
  x1 = rnorm(N),
  x2 = rnorm(N),
  z = 2*x1 + 3*x2 + rnorm(N),
  y = ifelse(z > mean(z), 1, 0), #2*x1 + 2*x2 + rnorm(1000)
  y_multi0 = case_when(z > (mean(z)+.2*sd(z)) ~ 0, z < (mean(z)-.2*sd(z)) ~ 2, T ~ 1),
  y_multi1 = y_multi0 + 1
) %>%
  glimpse
```


# Linear

```{r}
sp_linear <- split_sample(x = df[,c("x1", "x2")], id = df$split_id, y = df$z, meta = df)
sp_linear %>% iwalk(glimpse)
```


## keras

```{r, eval=F}
devtools::document()
li01 <- fit_learner(list(), sp_linear, task = "linear", backend = "keras")
li01$preds %>% glimpse
```


## xgboost

```{r, eval=F}
devtools::document()
li02 <- fit_learner(list(), sp_linear, task = "linear", backend = "xgboost")
# li02$preds %>% glimpse
# li02$metrics %>% glimpse
# li02$imps %>% glimpse
li02$save("test")
```


## ranger

```{r}
li03 <- fit_learner(list(), sp_linear, task = "linear", backend = "ranger")
li03$preds %>% glimpse
```

## catboost

```{r}
li04 <- fit_learner(list(iterations = 100), sp_linear, task = "linear", backend = "catboost")
li04$preds %>% glimpse
```

## rpart

```{r}
li05 <- fit_learner(list(), sp_linear, task = "linear", backend = "rpart")
li05$preds %>% glimpse
```

## randomForest

```{r}
li06 <- fit_learner(list(), sp_linear, task = "linear", backend = "randomForest")
li06$preds %>% glimpse
```


## h2o glm

```{r}
h2o::h2o.init()


dir("test")
devtools::document()
li07 <- fit_learner(list(), sp_linear, task = "linear", backend = "h2o_glm", path = "test")
#li07$preds %>% glimpse 
```


## h2o rf

```{r}
devtools::document()
li08 <- fit_learner(list(), sp_linear$splits, task = "linear", backend = "h2o_rf")
li08$preds %>% glimpse
```


## h2o gbm

```{r}
devtools::document()
fit2gbm <- fit_learner(list(), sp_linear$splits, task = "linear", backend = "h2o_gbm")
fit2gbm$preds %>% glimpse
```


## h2o xgboost

```{r}
devtools::document()
fit2xgboost <- fit_learner(list(), sp_linear$splits, task = "linear", backend = "h2o_xgboost")
fit2xgboost$preds %>% glimpse
```


## h2o dnn

```{r}
devtools::document()
fit1dnn <- fit_learner(list(), sp_linear$splits, task = "linear", backend = "h2o_dnn")
fit1dnn$preds %>% glimpse
```




# Binary

```{r}
sp_binary <- split_sample(x = df[,c("x1", "x2")], id = df$split_id, y = df$y, meta = df)
```


## keras

```{r}
# self <- list(
#   params = list(),
#   data = sp_linear$splits,
#   task = "linear", 
#   backend = "keras"
# )


fit20 <- fit_learner(list(), sp_binary, task = "binary", backend = "keras", path = "test")
fit20$preds %>% glimpse


sp_binary_cv <- split_sample(x = df[,c("x1", "x2")], id = , y = df$y, meta = df)
fit20 <- fit_cv(list(), sp_binary_cv, task = "binary", backend = "keras", path = "test")
fit20$preds %>% glimpse
```



## xgboost

```{r}
fit21 <- fit_learner(list(), sp_binary, task = "binary", backend = "xgboost")
fit21$preds %>% glimpse
```

## ranger

```{r}
fit22 <- fit_learner(list(), sp_binary, task = "binary", backend = "ranger")
fit22$preds %>% glimpse
```

## catboost

```{r}
fit23 <- fit_learner(list(iterations = 100), sp_binary, task = "binary", backend = "catboost")
fit23$preds %>% glimpse
```

## rpart

```{r}
fit24 <- fit_learner(list(), sp_binary, task = "binary", backend = "rpart")
fit24$preds %>% glimpse
```

## randomForest

```{r}
fit25 <- fit_learner(list(), sp_binary, task = "binary", backend = "randomForest")
fit25$preds %>% glimpse
```

## h2o glm

```{r}
library(h2o)
h2o.init()

devtools::document()
fit27 <- fit_learner(list(), sp_binary, task = "binary", backend = "h2o_glm")
fit27$preds %>% glimpse
fit27$imps
fit27$metrics
```

## h2o rf

```{r}
library(h2o)
h2o.init()

devtools::document()
fit28 <- fit_learner(list(), sp_binary, task = "binary", backend = "h2o_rf")
fit28$preds %>% glimpse
```

## h2o nb

```{r}
library(h2o)
h2o.init()

devtools::document()
fit29 <- fit_learner(list(), sp_binary, task = "binary", backend = "h2o_nb")
fit29$preds %>% glimpse
```


## h2o svm

```{r}
fit2svm <- fit_learner(list(), sp_binary, task = "binary", backend = "h2o_svm")
fit2svm$preds %>% glimpse
```


## h2o gbm

```{r}
devtools::document()
fit2gbm <- fit_learner(list(), sp_binary, task = "multi", backend = "h2o_gbm")
fit2gbm$preds %>% glimpse
```


## h2o xgboost

```{r}
devtools::document()
fit2xgboost <- fit_learner(list(), sp_binary, task = "binary", backend = "h2o_xgboost")
fit2xgboost$preds %>% glimpse
```



## h2o dnn

```{r}
devtools::document()
fit2dnn <- fit_learner(list(), sp_binary, task = "binary", backend = "h2o_dnn")
fit2dnn$preds %>% glimpse
```



# Multi

```{r}
sp_multi <- split_sample(x = df[,c("x1", "x2")], y = df$y_multi0, id = df$split_id, meta = df)
```


## keras

```{r, eval=F}
fit30 <- fit_learner(list(), sp_multi, task = "multi", backend = "keras")
fit30$preds %>% glimpse
```

## xgboost

```{r, eval=F}
devtools::document()
fit31 <- fit_learner(list(num_class = 3), sp_multi, task = "multi", backend = "xgboost")
fit31$metrics
```


## ranger

```{r}
fit32 <- fit_learner(list(), sp_multi, task = "multi", backend = "ranger")
fit32$preds %>% glimpse
```


## catboost

```{r}
fit33 <- fit_learner(list(iterations = 100), sp_multi, task = "multi", backend = "catboost")
fit33$preds %>% glimpse
```

## rpart

```{r}
#fit34 <- fit_learner(list(), sp_multi, task = "multi", backend = "rpart")
#fit34$preds %>% glimpse
```

## randomForest

```{r}
# fit25 <- fit_learner(list(), sp_multi, task = "multi", backend = "randomForest")
# fit25$preds %>% glimpse
```


## h2o glm

```{r}
library(h2o)
h2o.init()

devtools::document()
fit36 <- fit_learner(list(), sp_multi, task = "multi", backend = "h2o_glm")

fit36$preds %>% glimpse
```


## h2o rf

```{r}
library(h2o)
h2o.init()

devtools::document()
fit38 <- fit_learner(list(), sp_multi, task = "multi", backend = "h2o_rf")
fit38$preds %>% glimpse
```


## h2o nb

```{r}
devtools::document()
fit39 <- fit_learner(list(), sp_multi, task = "multi", backend = "h2o_nb")
fit39$preds %>% glimpse
```


## h2o gbm

```{r}
devtools::document()
fit3gbm <- fit_learner(list(), sp_multi, task = "multi", backend = "h2o_gbm")
fit3gbm$preds %>% glimpse
```


## h2o xgboost

```{r}
devtools::document()
fit3xgboost <- fit_learner(list(), sp_multi, task = "multi", backend = "h2o_xgboost")
fit3xgboost$preds %>% glimpse
```


## h2o dnn

```{r}
devtools::document()
fit3dnn <- fit_learner(list(), sp_multi, task = "multi", backend = "h2o_dnn")
fit3dnn$preds %>% glimpse
```




# Oridinal


```{r}
library(h2o)
h2o.init()

devtools::document()
fit37 <- fit_learner(list(), sp_multi, task = "ordinal", backend = "h2o_glm")
fit37$preds %>% glimpse
```




# Other

### Then Install R Package

```{r, eval = F}
# devtools::install_github("Microsoft/LightGBM", subdir = "R-package")
# devtools::install_github("Laurae2/lgbdl")
lgbdl::lgb.dl(commit = "master",
       compiler = "vs",
       repo = "https://github.com/microsoft/LightGBM")

library(lightgbm)
data(agaricus.train, package='lightgbm')
dtrain <- lgb.Dataset(as.matrix(mtcars[,1:2]), label=mtcars$vs)
params <- list(objective="regression", metric="l2")
model <- lgb.cv(params, dtrain, 10, nfold=5, min_data=1, learning_rate=1, early_stopping_rounds=10)


# devtools::install_github("gbm-developers/gbm3")
# library(gbm3)
# available_distributions()
# bern_dist <- gbm_dist("Bernoulli")
# 
# train_params <- training_params(num_trees = 2000, interaction_depth = 3, 
#                                 num_train=nrow(data), num_features = 3)
# fit <- gbmt(Y ~ X1 + X2 + X3, distribution=bern_dist, data=data, weights = w, 
#             offset=offset, train_params = train_params,
#             cv_folds=5, keep_gbm_data=TRUE)
```
