---
title: "Trainer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages

```{r}
pacman::p_load(tidyverse, purrr, furrr, lubridate, glue)
devtools::document()
#devtools::load_all()
options(scipen = 999)
# devtools::install()
```




# CV Test Data

```{r}
N <- 10000
df <- tibble(
  date = seq(as.Date('2017-01-01'), Sys.Date(), by = 1)[1:N],
  x1 = rnorm(N),
  x2 = rnorm(N),
  z = 2*x1 + 3*x2 + rnorm(N),
  y = ifelse(z > mean(z), 1, 0), #2*x1 + 2*x2 + rnorm(1000)
  y_multi0 = case_when(z > (mean(z)+.2*sd(z)) ~ 0, z < (mean(z)-.2*sd(z)) ~ 2, T ~ 1),
  y_multi1 = y_multi0 + 1
) %>%
  glimpse
```



* build new r6 class
* init directory check versions rebuild
* predict one month in advance only (beacause of feature constraints)



```{r}
t1 <- as_date("2018-01-01")
t2 <- as_date("2019-01-01")

tcv1 <- tcv$new("test_repo")
tcv1$feed(list(date=df$date, t1=t1, t2=t2))
tcv1$plan
tcv1$data %>% glimpse
tcv1$plot_plan()
tcv1$plot_progress()

tcv1$go_forward()
tcv1$go_back()
```


```{r}
d1 <- list(
  x = df[, c("x1", "x2")],
  y = df$y,
  date = df$date,
  t1 = as_date("2018-01-01"),
  t2 = as_date("2019-01-01")
)

fit_tcv(list(), d1, task = "binary", backend = "xgboost", path = "test_repo", n = 10)

c <- check_tcv(d1, "test_repo")

c$plot_plan()
c$plot_progress()
```









# Binary

```{r}
sp_binary <- split_sample(x = df[,c("x1", "x2")], id = df$split_cv, y = df$y, meta = df)
#sp_binary %>% iwalk(glimpse)
```


## CV

```{r}
devtools::document()
li01 <- fit_cv(list(epochs = 1), sp_binary, task = "binary", backend = "keras", path = "test")
li01$metrics %>% glimpse

li01$model
```


```{r}
hyper <- list(
  batch_size =  p_integer(30, 300)
)

# dials::value_seq(hyper_cnn_lstm$input_dim, 100)
params <- hyper %>% 
  dials::grid_random(size = 10) %>%
  dplyr::mutate(
    epochs = 1
  ) %>%
  as_tibble()

class(params)

c <- deeplyr::grid$new("exp")
funny <- function(params, data, path) fit_cv(params, data, task = "binary", backend = "keras", path)

c$run(
  data = sp_binary,
  process = funny, 
  params = params
)
```
