---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages

```{r}
pacman::p_load(tidyverse, purrr, furrr)
```


# Main Function

# Linear

```{r}
# linear_keras <- function(){
#   keras::keras_model_sequential() %>%
#     keras::layer_dense(units = 50, activation = "tanh", input_shape = 28) %>%
#     keras::layer_dense(units = 1, activation = "linear")
# }

devtools::document()
model_params <- list(
  output_dim = 1
  #model  = linear_keras
)

devtools::document()
f <- deeplyr::learner$new("xgboost:linear")
f$set_param(model_params)
f$set_data(x = games_features, y = games_all$goal_rate)
f$set_split()
#f$param
#f$splits %>% iwalk(~{print(.y); glimpse(.x)})
#f$splits$train$y %>% dummies::dummy()
f$train(cv = F)
f$splits$test

#pred <- f$test(dev = T)
f$test()
f$eval$perform
f$eval$plots
```

```{r}
e <- evaluator$new("linear")
e$eval(target = f$splits$test$target, pred)
e$preds
e$plots
```



# Binary 

```{r}
binary_keras <- function(){
  keras::keras_model_sequential() %>%
    keras::layer_dense(units = 50, activation = "tanh", input_shape = 28) %>%
    keras::layer_dense(units = 1, activation = "sigmoid")
}

devtools::document()
model_params <- list(
  output_dim = 1,
  target = "winner",
  model  = binary_keras
)

devtools::document()
f <- deeplyr::learner$new("keras:binary")
f$set_param(model_params)
f$set_data(x = games_features, y = games_all$winner_binary)
f$set_split()
#f$param
#f$splits %>% iwalk(~{print(.y); glimpse(.x)})
#f$splits$train$y %>% dummies::dummy()
f$train(cv = F)
pred <- f$test(dev = T)
```

```{r}
e <- evaluator$new("binary")
e$eval(target = f$splits$test$target, pred)
e$preds
e$plots
```

# Categorical 

```{r}
custom_keras <- function(){
  keras::keras_model_sequential() %>%
    keras::layer_dense(units = 50, activation = "tanh", input_shape = 46) %>%
    keras::layer_dense(units = 3, activation = "softmax")
}

devtools::document()
model_params <- list(
  output_dim = 3,
  target = "winner",
  model  = custom_keras,
  model_name = "custom"
)

devtools::document()
f <- deeplyr::learner$new("keras:categorical")
f$set_param(model_params)
f$set_data(x = games_lagged_features, y = games_lagged$winner)
f$set_split()
#f$param
#f$splits %>% iwalk(~{print(.y); glimpse(.x)})
#f$splits$train$y %>% dummies::dummy()
f$train(cv = F)
pred <- f$test(dev = T)
```




```{r}
e <- evaluator$new("categorical")
e$eval(target = f$splits$test$target, pred)
e$preds
#e$plots
```