---
title: "deeplyr"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, message = F, warning = F, error = F)
```

```{r, echo = F, results='asis'}
library(badger)
cat(
	badge_code_size("systats/deeplyr"),
	badge_last_commit("systats/deeplyr")
)
```

This is a light-weight model engine mainly for text classification tasks written as R6class. While Keras, XGBoost or Ranger (RF) provide high quality learners, `deeplyr` comes with unifying train/test/report functions for all backends mentioned. This streamlined data/ model worklfow does automatically 

<!-- * log (thanks to [`trackR`](https://github.com/daroczig/logger)),  -->
<!-- * benchmark (thanks to [`tictoc`]() and [`Metrics`]()) -->
<!-- * optimize over hyperparameter spaces.  -->


<!-- # Other stuff -->

<!-- * a roadmap for improved NLP decisions focussing on different outcomes (fortcomming). -->
<!-- * shinyapp for monitoring model performances. -->


# Options

```{r, eval = F}
# keras::install_keras()
# tensorflow::install_tensorflow()
# py_config()
# use_python("/anaconda3/lib/python3.7")
# py_install("tensorflow")
# Sys.getenv("RETICULATE_PYTHON")
```


```{bash, eval = F}
echo "Sys.setenv(RETICULATE_PYTHON = '~/usr/local/bin/python3')" > ~/.Rprofile
```

```{bash, eval = F}
nano ~/.Rprofile
```

