---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(devtools, R6, tidyverse, purrr, furrr, RSQLite, 
      # GA, dials,
      jsonlite, text2vec, keras, reticulate,
      plotROC, alluvial, ggforce, ggalluvial, ggparallel, survminer, survival)

options(scipen = 999)
devtools::load_all()
```

# Data

```{r}
dparams <- list(
  data_path = "../sample_dat.Rdata",
  text = "lemma",
  input_dim = 2000,
  term_count_min = 5,
  doc_proportion_max  = .1,
  sample = 50000
)

dc <- create_dtm_container(dparams)
```


# GA

```{r}
hyper <- list()
dials::new_quant_param(
  type = "integer",
  inclusive = c(T, T),
  range = c(64L, 256L),
  label = c(embed_dim = "# Embedding Dimension")
) -> hyper$keras_simple_mlp$embed_dim

dials::new_quant_param(
  type = "integer",
  inclusive = c(T, T),
  range = c(32L, 256L),
  label = c(dense_dim = "# Dense Layer Dimension")
) -> hyper$keras_simple_mlp$dense_dim

dials::new_quant_param(
  type = "double",
  inclusive = c(T, T),
  range = c(.01, .5),
  label = c(dropout = "# Dropout ratio")
) -> hyper$keras_simple_mlp$dropout

hyper$keras_simple_mlp
```


```{r}
static <- list(  
  epochs = 1,
  output_dim = 1, 
  output_fun = "sigmoid",
  target = "binary",
  loss = "binary_crossentropy",
  model = deeplyr::keras_simple_mlp,
  model_name = "simple_mlp",
  pooling = "global_average"
)

GA <- ga$new(mkdir = "simple_run1", backend = "keras:binary")
GA$set_data(dc_seq)
GA$set_param(static)
GA$set_hyper(hyper$keras_simple_mlp)
GA$optimize()
#GA$get_param()
```

