---
title: "test"
output: html_document
---



```{r}
# devtools::install_github("systats/deeplyr")
# features <- simon$con %>% get_users() %>% 
#   select(follow, contains("count"))
pacman::p_load(tidyverse, keras, xgboost, ranger)
devtools::document()
#devtools::install()


df <- tibble(
  id = sample(1:100, 1000, replace = T),
  split_id = sample(1:3, size = 1000, prob = c(.8, .1, .1), replace = T),
  x1 = rnorm(1000),
  x2 = rnorm(1000),
  z = 2*x1 + 3*x2,
  y = ifelse(z > mean(z), 1, 0), #2*x1 + 2*x2 + rnorm(1000)
  y12 = ifelse(z > mean(z), 2, 1) #2*x1 + 2*x2 + rnorm(1000)
) %>% 
  select(contains("x"), everything()) %>%
  glimpse
```


```{r}
#devtools::document()
mparams <- list(
  output_dim = 1
)

f <- learner$new("xgboost:binary")
f$set_param(mparams)
f$set_data(x = df[,1:2], y = df$y)
f$set_split()
f$trainer
f$train()
f$test(dev = F)

f$eval$preds
f$eval$plots
f$eval$perform

f$trainer$predict(f$splits$test$x)
```


```{r}
devtools::document()
mparams <- list(
  output_dim = 1
)

f <- learner$new("ranger:binary")
f$set_param(mparams)
f$set_data(x = df[,1:2], y = df$y)
f$set_split()
f$trainer
f$train()
#f$trainer$model
#f$test(dev = T)
f$test(dev = F)

f$eval$preds
f$eval$plots
f$eval$perform

f$trainer$predict(f$splits$test$x)
```




```{r}
# devtools::document()
custom_keras <- function(input_dim = 20, output_dim = 1, output_fun = "sigmoid"){
  keras::keras_model_sequential() %>%
    keras::layer_dense(units = 10, activation = "relu", input_shape = input_dim) %>%
    keras::layer_dense(units = output_dim, activation = output_fun)
}

mparams <- list(
  output_dim = 1,
  input_dim = 2, 
  epochs = 10,
  model = custom_keras
)

self <- learner$new("keras:binary")
self$set_param(mparams)
self$set_data(x = df[,4:5], y = df$y)
self$set_split()
self$train()
self$test(dev = F)

self$eval$perform
self$eval$preds
self$eval$plots

self$trainer$predict(f$splits$test$x)
```

